### ISSUE TITLE
Clojure compatibility

### ISSUE THREAD

**Issue by bilus** [copilot-emacs/copilot.el#229] opened 2024-01-07 13:51 UTC
I haven't tried the previous version but the latest one as of time of writing this, breaks Clojure by changing cursor position after a completion is ignored and I continue typing.

I have a fairly standard CIDER setup and the newest doom-emacs configuration so it should be fairly easy to reproduce but if you need more details, I'll be more than happy to provide them.

In Go it works beautifully, great job!

**Comment by gen1321** [comment] 2024-01-07 14:54
I have the same problem, it's strange.
Consider this example suggestion:

![Screenshot 2024-01-07 at 15 51 36](https://github.com/copilot-emacs/copilot.el/assets/1628415/9f215ac9-45c4-44d8-887e-17f8cae0dc7d)

if I type `d`, everything is fine
![Screenshot 2024-01-07 at 15 52 13](https://github.com/copilot-emacs/copilot.el/assets/1628415/de8b543a-bd8d-4d7a-93bf-e6addc1512a5)

However, when I type `e` after that 
![Screenshot 2024-01-07 at 15 53 17](https://github.com/copilot-emacs/copilot.el/assets/1628415/44889873-5b0e-4fc3-9aee-68f855b372a3)
I get a closing parenthesis, and e.

It's very annoying, and I can say that it's a new behavior, last couple month it was working just fine

**Comment by claytharrison** [comment] 2024-01-08 08:01
This may be somehow related to the jsonrpc error they're working on in #224. I have similar issues with copilot in Python after running a `doom upgrade`, and was getting an error related to continuation requests, as mentioned in [this Doom emacs issue](https://github.com/doomemacs/doomemacs/issues/7606). Only way I can keep coding for now is to turn copilot off.

**Comment by gen1321** [comment] 2024-01-08 12:17
I just upgraded to latest doom version wich includes fixes for `events-buffer-scrollback-size` error, however the issue still persists.

I am getting another warning about `copilot--infer-indentation-offset`, but  i am getting this one for a long time and it worked just fine, so i doubt that this is a reason

**Comment by claytharrison** [comment] 2024-01-08 16:49
Same here actually. I get the warning about `copilot--infer-indentation-offset` in elisp buffers (but NOT python buffers), except I never got these errors at all until a few days ago when I upgraded doom.

The parenthesis issue still persists in both elisp and python buffers however (have not tried any other languages).

**Comment by bclark-videra** [comment] 2024-01-08 17:21
This appears to have been introduced with #222.

**Comment by bilus** [comment] 2024-01-09 15:22
UPDATE: I'm getting similar problems in Go. Go integration USED to work great but not after the upgrade.

**Comment by emil-vdw** [comment] 2024-01-12 08:55
I have reverted the commit causing the bug (#233) for the time being. Can you confirm that the issue is no longer present on the latest commit?

**Comment by 1334** [comment] 2024-01-12 11:12
hi @emil-vdw I can confirm that everything is behaving as before after the revert. Thanks!

**Comment by emil-vdw** [comment] 2024-01-12 11:32
Resolved by #233

**Closed by emil-vdw** 2024-01-12 11:32 UTC
Labels: bug
